/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type * as erc721 from "./ERC721";
import type * as erc1155 from "./ERC1155";
import type * as common from "./common";

export type { erc1155 };

export type { erc721 };

export type { common };
export type { ERC20 } from "./ERC20";
