/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC1155Holder } from "./ERC1155Holder";
export type { ERC1155TokenReceiver } from "./ERC1155TokenReceiver";
